### PR TITLE
Add 18.6.0 documentation

### PR DESCRIPTION
**Pull request by jrha**
Built with build-quattor-documentation.sh

### CODE REVIEW

**Comment by jouvin** [comment]
@jrha not sure how to ensure that this PR is valid. But checks are failing with some invalid tags in `ncm-iptables` docs, so this is may be something to fix...

**Comment by jrha** [comment]
I know, they're not great, many of the problems come from pod2markdown.
It's auto generated, so the generator needs fixing, not sure how much it's worth it, as I think there is a rewrite which has been forgotten about (see #4).

**Comment by jrha** [comment]
I'll try forcing a newer version of `pod2markdown` to see if it helps...

**Comment by ned21** [comment]
Should we merge this to at least get some 18.6 docs generated?

**Comment by jrha** [comment]
I think so, I've pinged @wdpypere about the updated script.

**Comment by wdpypere** [comment]
@jrha the rewrite to rst was never completed. As far as I remember the script works for it generates weird ouput here and there because the templates need fixing.

**Comment by jrha** [comment]
Indeed, better to merge this and fix as we move forward.

**Pull request merged**
