### PR TITLE
Add 17.8.0 documentation

### PR DESCRIPTION
**Pull request by jrha**
Build 17.8.0 documentation on top of 17.7.0 documentation.

### CODE REVIEW

**Comment by jrha** [comment]
@wdpypere here's the interesting part:
The 17.8.0 docs I've built don't quite match the ones you built...
https://github.com/quattor/documentation/compare/master...jrha:17.8.0?expand=1

**Comment by wdpypere** [comment]
@jrha Mine were built from master, not from tagged version. did you just run https://github.com/quattor/release/blob/master/src/documentation_builder/bin/build-quattor-documentation.sh? because that was what I did.

**Comment by jrha** [comment]
Yes, but I modified it to use tagged versions, so that explains the difference

**Review by wdpypere — APPROVED** [review]

**Comment by ned21** [comment]
This is why I recommend putting "how I built this" in the commit message as even with auto-generated stuff it's easy to auto-generate something different from the previous person. :-)

**Pull request merged**
