### PR TITLE
publish default values when defined

### PR DESCRIPTION
**Pull request by wdpypere**
pan-annotations supports showing default values. Export these to the documentation.

### CODE REVIEW

**Comment by ned21** [comment]
Looks nice & I assume auto-generated. Would it be a good idea to include the command used to generate it in the commit log to allow someone to see how previous changes were created?

**Comment by wdpypere** [comment]
@ned21 This is indeed generated content. What would you want the commit message to look like? something like:
```Built using "build-quattor-documentation.sh" from https://github.com/quattor/release/tree/master/src/documentation_builder``` ?

**Comment by ned21** [comment]
@wdpypere Yes please! In fact, one better would be:

Built using version $tag of "build-quattor-documentation.sh" from
https://github.com/quattor/release/tree/master/src/documentation_builder

**Comment by wdpypere** [comment]
@ned21 commit message updated.

**Pull request merged**
