### PR TITLE
16.6.0 documentation

### PR DESCRIPTION
**Pull request by wdpypere**
Rebuilt for the 16.6.0 release. Aside various updates the following was removed:
- docs/CAF/replogger.md
- docs/CAF/reporterobject.md

and the following were added:
- docs/CAF/history.md
- docs/CAF/path.md
- docs/CAF/rulebasededitor.md
- docs/components/spma::yumng.md

A preview (based on latest master) can be seen here: http://docs-test-comps.readthedocs.io/en/latest/

After this is merged, this can be tagged and pushed to the official readthedocs documentation. I'll then make a PR to update the links on quattor.org as well.

### CODE REVIEW

**Comment by wdpypere** [comment]
hmm, travis does not seem to like the first build of this repo. 
after building locally with sphinx-builder there are indeed some errors in there which find there source in weird pod syntax used. I'll update this PR with the tests and fixes, and I'll see if I can fix the sources in the pods.

**Comment by jouvin** [comment]
Thanks for doing this. It would be great if we could announce it as the main source of information. I have seen two things that would be great to fix:
- Main page is an intro which is empty. A couple of sentences saying that this is the documentation of configuration modules and underlying components (CAF) would be great. And may with a link to the main Quattor documentation, making explicit this is not an introduction or how-to.
- I think I already reported it: it would have been great to have the documentation of the grid configuration modules the same way (from configuration-modules-grid repo). I guess this is too much for this release and in this case I'd prefer to see a first release without it and an issue to remember that we need to add them at the next iteration.

**Comment by wdpypere** [comment]
@jouvin The intro page should be updated in this PR (albeit it still quite small).
I'll see if I can get the grid modules in there, or maybe for next release.

**Comment by wdpypere** [comment]
@jouvin I created the issue for adding configuration-modules-grid.

So I added html checking on travis and fixed serveral linking issues (which I'll also fix in the sources/generator script).

So this is good to go.

**Comment by stdweird** [comment]
@wdpypere not sure if you me review all of this. e.g. `ncm-authconfig` still has urls to cpan; and on that page, there are also issues with names with `_` in them (like part of the config tree).

**Comment by stdweird** [comment]
@wdpypere thanks for updating the url.
LGTM

**Comment by stdweird** [comment]
@jrha who runs quattor.org?

```
- ./site/index.html
  *  External link https://www.quattor.org/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL peer certificate or SSH remote key was not OK
```

**Comment by wdpypere** [comment]
@stdweird reverted to http. Indeed, firefox also does not like quattor.org on https.

**Comment by stdweird** [comment]
tracking the https://quattor.org issue in https://github.com/quattor/quattor.github.com/issues/185

**Comment by wdpypere** [comment]
@jouvin I added configuration-modules-grid. I built a preview here: http://docs-test-comps.readthedocs.io/en/latest/

**Comment by stdweird** [comment]
@wdpypere the grid docs are not on that url.

**Comment by wdpypere** [comment]
@stdweird yes they are, for instance: http://docs-test-comps.readthedocs.io/en/latest/components-grid/yaim/
Just hit F5 until firefox decides the magic number for invalidating its cache is reached. :wink:

**Comment by wdpypere** [comment]
fixes #3

**Comment by wdpypere** [comment]
@jrha Can you have a look? would be nice to publish. :wink:

**Comment by stdweird** [comment]
@jrha i'm going to merge this and send to mailing list. any remarks can be used as input for the 16.8 docs 
@wdpypere big thanks!

**Comment by jrha** [comment]
@wdpypere thanks!

**Pull request merged**
