### PR TITLE
regenerate documentation since 17.2.0

### PR DESCRIPTION
**Pull request by wdpypere**

### CODE REVIEW

**Review by stdweird — APPROVED** [review]

**Comment by wdpypere** [comment]
hmm, I don't understand why stravis should fall over this external link:
```
External link https://readthedocs.org failed: response code 0 means something's wrong.
```
That link is fine in my browser. @jrha any ideas?

**Comment by wdpypere** [comment]
on my laptop the tests run fine.

**Comment by ned21** [comment]
My guess would be that readthedocs.org block requests from travis due to too many things testing it.

**Comment by jrha** [comment]
I think @ned21 is probably correct. Given that the intended target of this documentation is readthedocs we should be able to safely assume that links to there do not need checking, so you could add `--url-ignore "/readthedocs.org/"` to the `html-proofer` args.

**Comment by wdpypere** [comment]
Adding the url-ignore indeed fixed the problem. thanks!

**Comment by jrha** [comment]
Cool. Is this built from HEAD? 17.8 was published last week...

**Comment by wdpypere** [comment]
This is from head from last Thursday. I can do a rebuild with for 17.8 specifically if you want. 
I want to add the default values soon anyway (when this gets in: https://github.com/quattor/release/pull/311 ).

**Pull request merged**
