### PR TITLE
Add 17.12.0 documentation

### PR DESCRIPTION
**Pull request by jrha**
Built with `quattor-documentation-builder -c -m src/ -o output/ --info` with some cleanup and whitespace trimming.

First part of quattor/release#66.

### CODE REVIEW

**Comment by jrha** [comment]
Stupid garbage HTML tags get created by `< … >` in docs... will look at doing some additional cleanup.

**Comment by stdweird** [comment]
@jrha also use https://jenkins0.ugent.be/job/panc/org.quattor.pan$panc/ so default values from the schema are added to the docs

**Comment by jrha** [comment]
Eh?

**Comment by stdweird** [comment]
there's no pan release that has support for generating annotations that have the defautl value from the schema (https://github.com/quattor/pan/pull/169), so you have to use one of the jars from latest master

**Comment by jrha** [comment]
Ah ok.

**Comment by jrha** [comment]
After chasing around for a while I realised these ARE built with a compiler that includes default values, as were the previous versions of the docs.

**Comment by jrha** [comment]
I've wasted most of the afternoon trying to figure this out and I'm giving up, there is clearly something missing from what I am running versus what @wdpypere did to build the docs in **master**, as things stand a fair amount of the docs will be seen as bogus HTML tags and be invisible.

If you want something better, make @wdpypere do it.

**Comment by jrha** [comment]
@stdweird I don't think can be improved without input from @wdpypere and the next release is overdue, so we should probably just merge...

**Comment by jrha** [comment]
@jouvin this PR

**Pull request merged**
